baseurl = "https://dak.sh/"
# remember trailing / at end of baseurl
languageCode = "en"
title = "ln(Daksh)"
desc = "natural log of my thoughts."
# Enable comments by entering your Disqus shortname
disqusShortname = "dak-sh"
paginate = 3

# theme
theme = "hyde-hyde"
relatedPosts = true

[params]
  author = 'Daksh Miglani'
  title = 'ln(Daksh)'
  description = 'natural log of my thoughts!'
  dateformat = "Jan 2, 2006"

  # sidebar, copyright & license
  copyright = "DakshMiglani"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = false

  # https://highlightjs.org
  highlightjs = true
  highlightjsstyle = "github"

[params.social]
twitter = 'Dak_ssh'
github = 'DakshMiglani'
email = 'hello@dak.sh'
telegram = 'DakshMiglani'
linkedin = 'dakshmiglani'
stackoverflow = '6792646'

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About Me"
    identifier = "about-me"
    weight = 300
    url = "/posts/about-me"
